DnD - Campaign Dashboard v.1/DnD - Campaign Dashboard v.1/Models/Campaign.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DnD___Campaign_Dashboard_v._1.Models
{
    public class Campaign : ParentClass
    {
        //Data annotation to be used in validation of properties, sets the character length to 1000
        [StringLength(1000)]
        public string Story { get; set; }

        //Data annotation to be used in validation of properties, sets the character length to 1000
        [StringLength(1000)]
        public string Note { get; set; }
        
        ////Creates a list of encounters that will serve as the fights, boss battles of the campaign
        //public List<Encounter> Encounters { get; set; }
        
        //Represents the dungeon master user ID, so we can check if the person viewing the campaign
        //is the one that created it and then pass the correct view
        [Required]
        public string DMUserId { get; set; }
        
        [Required]
        [Display(Name = "Date Created")]
        public DateTime DateCreated { get; set; }
    }
}

DnD - Campaign Dashboard v.1/DnD - Campaign Dashboard v.1/Models/CampaignViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DnD___Campaign_Dashboard_v._1.Models
{
    public class CampaignViewModel
    {
        //View models are used to pass multiple objects and parameters to views
        public InvitationModel Invitation { get; set; }
        public List<Character> Characters { get; set; }
        public List<Encounter> Encounters { get; set; }
        public Campaign Campaign { get; set; }
        public List<Campaign> Campaigns { get; set; }
    }
}

DnD - Campaign Dashboard v.1/DnD - Campaign Dashboard v.1/Controllers/CampaignController.cs
using DnD___Campaign_Dashboard_v._1.Models;
using System;
using Microsoft.AspNet.Identity;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SendGrid;
using Microsoft.AspNet.Identity.Owin;
using System.Threading.Tasks;
using System.Net;

namespace DnD___Campaign_Dashboard_v._1.Controllers
{
    [Authorize]
    public class CampaignController : Controller
    {
        private ApplicationDbContext _context;
        
        //Instantiates a new instance of Db Context used to query the database
        public CampaignController()
        {
            _context = new ApplicationDbContext();
            
        }

        // GET: Campaign
        public ActionResult Index()
        {
                       
            var campaigns = _context.Campaigns.ToList();
            
            return View(campaigns);           
        }
        
        //Allows users to create new campaign
        public ActionResult New()
        {
            var characters = _context.Characters.ToList();
            //Instantiates new campaign view model to pass multiple objects back to view
            var viewModel = new CampaignViewModel
            {
                Characters = characters,
                Campaign = new Campaign()
            };

            return View("New", viewModel);
            //return View();
        }

        //Method used when the new campaign form is submitted
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(Campaign campaign)
        {
            campaign.DateCreated = DateTime.Now;
            campaign.DMUserId = User.Identity.GetUserId();
            _context.Campaigns.Add(campaign);
            _context.SaveChanges();

            return RedirectToAction("Index");
            //return View();
        }

        //Replaces the INDEX action, instead uses Tabs view to make UI more streamlined and intuitive
        public ActionResult Tabs(int id)
        {
            //Initialises objects to be loaded into view model
            var encounters = _context.Encounters.Where(e => e.CampaignId == id).ToList();
            InvitationModel invitation = new InvitationModel() { Campaign_Id = id, UserId = User.Identity.GetUserId() };
            Campaign campaign = _context.Campaigns.Find(id);
            var characterSheets = _context.Characters.Where(t => t.Campaign_Id == id).ToList();

            //Instrantiates new view model to pass objects to view
            CampaignViewModel campaignViewModel = new CampaignViewModel
            { 
                Campaign = campaign, 
                Characters = characterSheets, 
                Invitation = invitation, 
                Encounters = encounters 
            };

            return View(campaignViewModel);
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Campaign campaign = _context.Campaigns.Find(id);
            if (campaign == null)
            {
                return HttpNotFound();
            }
            return View(campaign);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Campaign campaign)
        {
            if (ModelState.IsValid)
            {
                _context.Entry(campaign).State = EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction("View", new { id = campaign.Id });
            }
            return View(campaign);
        }

        // GET: /Campaign/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Campaign campaign = _context.Campaigns.Find(id);
            if (campaign == null)
            {
                return HttpNotFound();
            }
            return View(campaign);
        }

        // POST: /Campaign/Delete/5
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Campaign campaign = _context.Campaigns.Find(id);
            if (User.Identity.GetUserId() == campaign.DMUserId)
            {
                _context.Campaigns.Remove(campaign);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("Error");
        }

        public ActionResult NewEncounter()
        {
            return View();
        }

    }
}

DnD - Campaign Dashboard v.1/DnD - Campaign Dashboard v.1/Controllers/EncounterController.cs
using DnD___Campaign_Dashboard_v._1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DnD___Campaign_Dashboard_v._1.Controllers
{
    public class EncounterController : Controller
    {
        private ApplicationDbContext _context;
        //Instantiates a new instance of Db Context used to query the database
        public EncounterController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: Encounters
        public ActionResult Index()
        {
            return View();
        }
        
        //Adds encounters to the database
        public ActionResult AddEncounter(Encounter encounter)
        {
            _context.Encounters.Add(encounter);
            _context.SaveChanges();
            

            return RedirectToAction("View","Campaign",new { id = encounter.CampaignId });
        }
    }
}

DnD - Campaign Dashboard v.1/DnD - Campaign Dashboard v.1/Controllers/InvitationController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using DnD___Campaign_Dashboard_v._1.Models;

namespace DnD___Campaign_Dashboard_v._1.Controllers
{
    public class InvitationController : Controller
    {
        private ApplicationUserManager _userManager;

        public InvitationController() { }

        public InvitationController(ApplicationUserManager userManager)
        {           
            UserManager = userManager;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        
        //Method for sending an invitation email, users a developer's email
        [HttpPost]
        public async Task<ActionResult> SendEmailAsync(InvitationModel invitation)
        {
            
            //Defines properties  of the email sent to the one being invited
            IdentityMessage email = new IdentityMessage
            {
                Destination = invitation.Email,
                Subject = "You have been invited to join a DnD Campaign",
                Body = "In order to accept the invitation you must first visit our site and make sure that you arleady have a verified account. Then move on to Character Sheets option from the left menu bar and choose Create New. Feel free to create your own Character and don't forget to include the Campaign Id which is: " + invitation.Campaign_Id
            };

            await UserManager.EmailService.SendAsync(email);



            return RedirectToAction("Tabs", "Campaign", new { id = invitation.Campaign_Id });
        }
    }
}

DnD - Campaign Dashboard v.1/DnD - Campaign Dashboard v.1/Views/Campaign/Delete.cshtml
@model DnD___Campaign_Dashboard_v._1.Models.Campaign

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Campaign</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Story)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Story)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DMUserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DMUserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DnD - Campaign Dashboard v.1/DnD - Campaign Dashboard v.1/Views/Campaign/Edit.cshtml
@model DnD___Campaign_Dashboard_v._1.Models.Campaign

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Campaign</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Story, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Story, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Story, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateCreated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateCreated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateCreated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DnD - Campaign Dashboard v.1/DnD - Campaign Dashboard v.1/Views/Campaign/Index.cshtml
@model IEnumerable<DnD___Campaign_Dashboard_v._1.Models.Campaign>
@using Microsoft.AspNet.Identity;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css">

<h2>Campaigns</h2>


<p>
    @Html.ActionLink("Create New", "New", null, new { @class = "btn btn-primary" })
</p>
<table id="characters" class="table table-bordered table-hover" style="width:100%">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateCreated)
            </th>
            <th>Options</th>

        </tr>
    </thead>
    
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateCreated.Date)
                </td>
                <td>
                    @Html.ActionLink("View", "Tabs", new { id = item.Id })
                    @if (item.DMUserId == User.Identity.GetUserId())
                    {
                        <span> | </span>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                    }
                    @if (item.DMUserId == User.Identity.GetUserId())
                    {
                        <span> | </span>
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    }

                </td>
            </tr>
        }
    </tbody>

</table>

@section scripts
    {
    <script type="text/javascript">
        $(document).ready(function () {
            $('#characters').DataTable();
        });
    </script>

    <script src='https://code.jquery.com/jquery-3.5.1.js'></script>
    <script src='https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js'></script>

}

DnD - Campaign Dashboard v.1/DnD - Campaign Dashboard v.1/Views/Campaign/New.cshtml
@model DnD___Campaign_Dashboard_v._1.Models.CampaignViewModel
@{
    ViewBag.Title = "New Campaign";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>New Campaign</h2>
@using (Html.BeginForm("Save", "Campaign"))
{
    @Html.ValidationSummary(true, "Please fix the following errors!")
    <div class="form-group">
        @Html.LabelFor(c => c.Campaign.Name)
        @Html.TextBoxFor(c => c.Campaign.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.Campaign.Name)
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.Campaign.Story)
        @Html.TextAreaFor(c => c.Campaign.Story, new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.Campaign.Story)
    </div>
    @*<div class="form-group">
        @Html.LabelFor(c => c.Campaign.Characters)
        @Html.DropDownListFor(m => m.Campaign.Characters, new SelectList(Model.Characters, "Id", "charname"), "Select Characters", new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.Campaign.Characters)
    </div>*@
    @*<div class="form-group">
        @Html.LabelFor(c => c.Campaign.Characters)
        @Html.DropDownListFor(m => m.Campaign.Characters, new SelectList(Model.Characters, "Id", "Name"), "Select Characters", new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.Campaign.Characters)
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.Campaign.Characters)
        @Html.DropDownListFor(m => m.Campaign.Characters, new SelectList(Model.Characters, "Id", "Name"), "Select Characters", new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.Campaign.Characters)
    </div>*@
    @Html.AntiForgeryToken()
    <button type="submit" class="btn btn-primary">Save</button>
}

DnD - Campaign Dashboard v.1/DnD - Campaign Dashboard v.1/Views/Campaign/NewEncounter.cshtml
@model DnD___Campaign_Dashboard_v._1.Models.Encounter
@{
    ViewBag.Title = "New Encounter";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>New Encounter</h2>

@using (Html.BeginForm("AddEncounter", "Encounter"))         
{
    @Html.ValidationSummary(true, "Please fix errors ont he form!")
    <div class="form-group">
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Name)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Alignment)
        @Html.TextBoxFor(m => m.Alignment, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Alignment)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Size)
        @Html.TextBoxFor(m => m.Size, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Size)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Difficulty)
        @Html.TextBoxFor(m => m.Difficulty, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Difficulty)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.CampaignId)
        @Html.TextBoxFor(m => m.CampaignId, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.CampaignId)
    </div>
    @Html.HiddenFor(m => m.Id)
    @Html.AntiForgeryToken()
    <button type="submit" class="btn btn-primary">Add</button>
}

DnD - Campaign Dashboard v.1/DnD - Campaign Dashboard v.1/Views/Campaign/Tabs.cshtml
@model DnD___Campaign_Dashboard_v._1.Models.CampaignViewModel

@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<html>
<body>
    <br />
    <div>
        <h4>Campaign Name: @Html.DisplayFor(model => model.Campaign.Name)</h4>
    </div>

    <!-- Tab Buttons -->
    <ul id="tabstrip" class="nav nav-tabs" role="tablist">
        <li class="active">
            <a href="#_Info" role="tab" data-toggle="tab">Info</a>
        </li>
        <li>
            <a href="#_CharacterListPartial" role="tab" data-toggle="tab">Characters</a>
        </li>
        <li>
            <a href="#_EncounterListPartial" role="tab" data-toggle="tab">Encounters</a>
        </li>
        <li>
            <a href="#_Chat" role="tab" data-toggle="tab">Chat</a>
        </li>
    </ul>

    <!-- Tab Content Containers -->
    <div class="tab-content">
        <div class="tab-pane fade in active" id="_Info">
            <br />
            <!-- Call partial view to load initial page load data -->
            @Html.Partial("_Info", Model.Campaign)
        </div>

        <div class="tab-pane fade" id="_CharacterListPartial">
            <br />
            @if (Model.Characters.Count != 0)
            {
                @Html.Partial("_CharacterListPartial", Model.Characters)
            }
            else
            {
                <div>
                    <h4>No players assigned yet! Invite your friends by using our invitation function!</h4>
                </div>
            }
            <div>
                @Html.Partial("_Invitation", Model.Invitation)
            </div>
        </div>

        <div class="tab-pane fade" id="_EncounterListPartial">
            <br />
            @Html.ActionLink("Add Encounter", "NewEncounter", null, "Encounter", new { @class = "btn btn-primary" })

            <h2></h2>

            @if (Model.Encounters.Count != 0)
            {
                @Html.Partial("_EncounterListPartial", Model.Encounters)
            }
            else
            {
                <div>
                    <h4>No encounters assigned yet!</h4>
                </div>
            }
        </div>

        <div class="tab-pane fade" id="_Chat">
            <br />
            @Html.Partial("_Chat")
        </div>
    </div>
    @Html.ActionLink("Back To List","Index",null, new { @class = "btn btn-primary" })
    <script>
        @*Jquery that render and handles tab functionality*@
        $(document).on("ready", function () {
            $('#tabstrip a').click(function (e) {
                e.preventDefault()
                var tabID = $(this).attr("href").substr(1);

                @*Fethes data via AJAX call*@
                $.ajax({
                    url: "/Campaign/" + tabID,
                    cache: false,
                    type: "get",
                    dataType: "html",
                    success: function (result) {
                        $("#" + tabID).html(result);
                    }
                })
                $(this).tab('show')
            });
        });
    </script>
</body>
</html>

DnD - Campaign Dashboard v.1/DnD - Campaign Dashboard v.1/Views/Campaign/_CharacterListPartial.cshtml
@model IEnumerable<DnD___Campaign_Dashboard_v._1.Models.Character>



<link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css">



<table id="charactersPartial" class="table table-bordered table-hover" style="width:100%">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.charname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.classlevel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.background)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.playername)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.race)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.alignment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.experiencepoints)
            </th>
            <th>Options</th>

        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.charname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.classlevel)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.background)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.playername)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.race)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.alignment)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.experiencepoints)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { controller = "CharacterSheet", id = item.Id }) |
                    @Html.ActionLink("View", "Details", new { controller = "CharacterSheet", id = item.Id })
                </td>
            </tr>
        }
    </tbody>

</table>

@section scripts
    {
    <script type="text/javascript">
        $(document).ready(function () {
            $('#charactersPartial').DataTable();
        });
    </script>

    <script src='https://code.jquery.com/jquery-3.5.1.js'></script>
    <script src='https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js'></script>

}



@*|
    @Html.ActionLink("Delete", "Delete", new { id = item.Id })*@

DnD - Campaign Dashboard v.1/DnD - Campaign Dashboard v.1/Views/Campaign/_Chat.cshtml
<html>
<head>
    <script src="~/Scripts/jquery.signalR-2.4.0.min.js"></script>
    <script src="~/signalr/hubs"></script>
</head>
<body>
    <div id="usernameForm">
        <br />

        <form>
            <div class="form-group">
                <label for="username">Enter your Username</label>
                <input type="text" class="form-control" id="username" placeholder="Username">
            </div>
            <button type="button" class="btn btn-primary" id="startChatBtn">Start Chat</button>
        </form>
    </div>

    <br />

    <div class="messaging" id="chatWindow">
        <div class="inbox_msg">
            <div class="mesgs">
                <div class="msg_history" id="messageList">

                </div>
                <div class="type_msg">
                    <div class="input_msg_write">
                        <input type="text" class="write_msg" id="sendMessageText" placeholder="Type a message" />
                        <button class="msg_send_btn" id="sendMessageBtn" type="button">
                            <img src="~/Content/DataTables/images/sort_asc_disabled.png" />
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        var chatHub = $.connection.chatHub;
        console.log(chatHub);
        var username = '';
        $('#chatWindow').hide();

        $('#startChatBtn').click(function () {
            username = $('#username').val();
            $('#chatWindow').show();
            $('#usernameForm').hide();
        });

        $('#sendMessageBtn').click(function () {
            chatHub.server.newMessage(username, $('#sendMessageText').val())
            makeOutgoingMessage($('#sendMessageText').val());
            $('#sendMessageText').val('');
        })

        function makeOutgoingMessage(message) {
            var newMsg = $('<div class="outgoing_msg"><div class="sent_msg"><p class="msg_body"></p><span class="msg_sub_text"></span></div></div>');
            newMsg.find('.msg_body').text(message);
            newMsg.find('.msg_sub_text').text("Sent by " + username);
            $('#messageList').append(newMsg);
        }

        function makeIncomingMessage(message, sender, date) {
            var newMsg = $('<div class="incoming_msg"><div class="received_msg"><div class="received_withd_msg"><p class="msg_body"></p><span class="msg_sub_text"></span></div></div></div>');
            newMsg.find('.msg_body').text(message);
            newMsg.find('.msg_sub_text').text("Sent by " + sender + " on " + new Date(date));
            $('#messageList').append(newMsg);
        }

        chatHub.client.sentMessage = function (username, message, date) {
            makeIncomingMessage(message, username, date)
        }
        $.connection.hub.start().done(function () {
            console.log('Connected to hubs!');
        })
    </script>
</body>
</html>

DnD - Campaign Dashboard v.1/DnD - Campaign Dashboard v.1/Views/Campaign/_EncounterListPartial.cshtml
@model IEnumerable<DnD___Campaign_Dashboard_v._1.Models.Encounter>



<link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css">



<table id="encounterPartial" class="table table-bordered table-hover" style="width:100%">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Alignment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Size)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Difficulty)
            </th>

        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Alignment)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Size)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Difficulty)
                </td>              
            </tr>
        }
    </tbody>

</table>

@section scripts
    {
    <script type="text/javascript">
        $(document).ready(function () {
            $('#encounterPartial').DataTable();
        });
    </script>

    <script src='https://code.jquery.com/jquery-3.5.1.js'></script>
    <script src='https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js'></script>

}

DnD - Campaign Dashboard v.1/DnD - Campaign Dashboard v.1/Views/Campaign/_Invitation.cshtml
@model DnD___Campaign_Dashboard_v._1.Models.InvitationModel
@using Microsoft.AspNet.Identity;



@using (Html.BeginForm("SendEmailAsync", "Invitation", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-offset-0" style="padding-left:20px">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })                 
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
            @Html.HiddenFor(m => m.Campaign_Id)
            @Html.HiddenFor(m => m.UserId)
        </div>

        <div>
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Invite" class="btn btn-default" id="invBtn" placeholder="Insert a valid email address.."/>
                <script>
                    $("#invBtn").click(function () {
                        alert("Invitation has been sent!");
                    });
                </script>
            </div>
        </div>
    </div>
}