DnD - Campaign Dashboard v.1/DnD - Campaign Dashboard v.1/Controllers/ArmourController.cs
using DnD___Campaign_Dashboard_v._1.Models.ArmorModelsApi;
using DnD___Campaign_Dashboard_v._1.Models.MagicItemModelsApi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace DnD___Campaign_Dashboard_v._1.Controllers
{
    public class ArmourController : Controller
    {
        private ArmorsModel armors;
        private ArmorModel armor;
        // GET: Armors
        [Authorize]
        public ActionResult Index()
        {
            using (var client = new HttpClient())
            {
                //Set the Uri
                client.BaseAddress = new Uri("https://www.dnd5eapi.co/api");

                //Get Async the respornse of the request and store it
                var responseTask = client.GetAsync("equipment-categories/armor");
                //Wait to fetch the data
                responseTask.Wait();

                //From the response, take only the Result
                var result = responseTask.Result;
                //if statement: 200(OK) Status Code
                if (result.IsSuccessStatusCode)
                {
                    //Read Async all the data and fetch only those which are relate to our model
                    var readTask = result.Content.ReadAsAsync<ArmorsModel>();
                    //Wait to fetch the data
                    readTask.Wait();

                    //Store the results to the private property
                    armors = readTask.Result;

                    
                }
                else
                {
                    //Construct a new object of the speficic type
                    armors = new ArmorsModel();

                    //Add an error to Model State
                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }
            }
            //return to the View the specified model that occurs, from the API call
            return View(armors.Equipment);
        }
        // GET: Armor
        [Authorize]
        public ActionResult Details(string id)
        {


            using (var client = new HttpClient())
            {
                //Set the Uri
                client.BaseAddress = new Uri("https://www.dnd5eapi.co/api/");

                //Get Async the respornse of the request and store it 
                var responseTask = client.GetAsync("equipment/" + id);
                //Wait to fetch the data
                responseTask.Wait();

                //From the response, take only the Result
                var result = responseTask.Result;
                //if statement: 200(OK) Status Code
                if (result.IsSuccessStatusCode)
                {
                    //Read Async all the data and fetch only those which are relate to our model
                    var readTask = result.Content.ReadAsAsync<ArmorModel>();
                    //Wait to fetch the data
                    readTask.Wait();

                    //Store the results to the private property
                    armor = readTask.Result;
                }
                else if (!result.IsSuccessStatusCode)
                {
                    //if the result has unsuccesful status code, redirect to the magic items controller
                    return RedirectToAction("Details", "MagicItems", new { id });
                }
                else
                {
                    //Add an error to Model State
                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }
            }
            //return to the View the specified model that occurs, from the API call
            return View(armor);
        }
    }
}

DnD - Campaign Dashboard v.1/DnD - Campaign Dashboard v.1/Views/Armour/Details.cshtml
@model DnD___Campaign_Dashboard_v._1.Models.ArmorModelsApi.ArmorModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Html.DisplayFor(model => model.name)</h2>

<div>
    <h4>Details</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.equipment_category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.equipment_category.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.armor_category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.armor_category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.armor_class)
        </dt>

        <dd></dd>

        <dt>
            @Html.DisplayNameFor(model => model.armor_class.Base)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.armor_class.Base)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.armor_class.dex_bonus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.armor_class.dex_bonus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.armor_class.max_bonus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.armor_class.max_bonus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.str_minimum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.str_minimum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.stealth_disadvantage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.stealth_disadvantage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost.Quantity) @Html.DisplayFor(model => model.Cost.Unit)
        </dd>

    </dl>
</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |*@
    @Html.ActionLink("Back to List", "Index", "Armour", new { @class = "btn btn-primary" })
</p>

DnD - Campaign Dashboard v.1/DnD - Campaign Dashboard v.1/Views/Armour/Index.cshtml
@{ ViewBag.Title = "Armours";
    Layout = "~/Views/Shared/_Layout.cshtml"; }

<h2>Armours</h2>

@*This defines a standard HTML table that is devoid of data. The column headers are coded in, alongside the
    bootstrap style class*@
<table id="armors" class="table table-bordered table-hover">
    <thead>
        <tr>

            <th>Armor</th>
            <th></th>

        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

@*Here the jQuery script is kept that is used to render a DataTable with the data collected from the API.*@
@section scripts
    {
    <script type="text/javascript">
        $(document).ready(function () {
            @* Here an ajax call is used to fetch a list of names for each entity.Also gathered is the index, which serves as the unique
            identifier of each entity in the API.*@
            $.ajax({
                url: 'https://www.dnd5eapi.co/api/equipment-categories/armor',
                type: 'GET',
                dataType: 'json',
                success: function (data) {
                    bindtoDatatable(data.equipment);
                }
            });
        });
        @* Function for assigning the data to the table.The colums are defined here alongside the data to be displayed in them *@
        function bindtoDatatable(data) {
            var table = $('#armors').dataTable({
                "bAutoWidth": true,
                "aaData": data,
                "columns": [

                    {
                        "data": "name"
                    },
                    {
                        @* Here, using the index gathered from the ajax call, it is passed back to the appropriate controller.
                            The index is then added onto the end of a URL, that is used to query the specific data of the entity *@
                        "data": "index",
                        render: function (data) {
                            return "<a href='../Armour/Details/" + data + "'>Details</a>"
                        }
                    }
                ]
            });
        }
    </script>
}