DnD - Campaign Dashboard v.1/DnD - Campaign Dashboard v.1/Controllers/DiceRollerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DnD___Campaign_Dashboard_v._1.Controllers
{
    public class DiceRollerController : Controller
    {
        // returns view for the Jscript dicew roller
        public ActionResult Index()
        {
            return View();
        }
    }
}

DnD - Campaign Dashboard v.1/DnD - Campaign Dashboard v.1/Controllers/EncounterController.cs
using DnD___Campaign_Dashboard_v._1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DnD___Campaign_Dashboard_v._1.Controllers
{
    public class EncounterController : Controller
    {
        private ApplicationDbContext _context;
        //Instantiates a new instance of Db Context used to query the database
        public EncounterController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: Encounters
        public ActionResult Index()
        {
            return View();
        }
        
        //Adds encounters to the database
        public ActionResult AddEncounter(Encounter encounter)
        {
            _context.Encounters.Add(encounter);
            _context.SaveChanges();
            

            return RedirectToAction("View","Campaign",new { id = encounter.CampaignId });
        }
    }
}

DnD - Campaign Dashboard v.1/DnD - Campaign Dashboard v.1/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/styles.css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://kit.fontawesome.com/b99e675b6e.js"></script>
</head>
<body>
    @*This section creates the sidebar visible on every page, kept in the _Layout file as it is common to all pages*@
    <div class="wrapper">
        <div class="sidebar">
            <ul>
                <li style="padding-left: 60px"><a href='@Url.Action("Index", "Home", "Landing Page")' target="_self"><img src="~/Images/Icon awesome-dice-d20.png" /></a></li>
            </ul>
            @*Checks that the user has logged in the site before displaying the feature navigation buttons*@
            @if (Request.IsAuthenticated)
            {
                <ul>
                    <li>@Html.ActionLink("Character Sheet", "Index", "CharacterSheet")</li>
                    <li>@Html.ActionLink("Campaign", "Index", "Campaign")</li>
                    <li>@Html.ActionLink("Dice Roller", "Index", "DiceRoller")</li>
                    <li>@Html.ActionLink("Encounters", "Index", "Encounter")</li>
                    <li>@Html.ActionLink("Monsters", "Index", "Monsters")</li>
                    <li>@Html.ActionLink("Spells", "Index", "Spells")</li>
                    <li>@Html.ActionLink("Magic Items", "Index", "MagicItems")</li>
                    <li>@Html.ActionLink("Weapons", "Index", "Weapons")</li>
                    <li>@Html.ActionLink("Armour", "Index", "Armour")</li>
                    <li>@Html.ActionLink("Adventuring Gear", "Index", "AdventuringGear")</li>
                </ul>
            }
            <strong>@Html.Partial("_LoginPartial")</strong>
            @*Placehold buttons for social media, upon publication of the site these would be linked to the appropriate page*@
            <div class="social_media">
                <a href="#"><i class="fab fa-facebook-f"></i></a>
                <a href="#"><i class="fab fa-twitter"></i></a>
                <a href="#"><i class="fab fa-instagram"></i></a>
            </div>
        </div>


        @*Renders the bundles required for this page to function correctly*@
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)


        <div class="main_content">
            <div class="body-content" style="padding: 20px"> @RenderBody() </div>
          
            <div class="navbar-fixed-bottom" style="padding-left: 10px; color:#f3f5f9">
                <footer>
                    <p>&copy; @DateTime.Now.Year <br/> DND Management Systems</p>
                </footer>
            </div>
          
        </div>

    </div>
</body>
</html>